-- Bug fix, found while building the Program Library feature: package_exercises
-- was created with `package_id` doing triple duty — identity-generated
-- column, primary key, AND the FK to packages.id. Since a primary key must
-- be unique per row, that made it structurally impossible for a package to
-- ever contain more than one exercise (a second row with the same
-- package_id violates the PK). saveBuilderPlan's "protocol" save path
-- already inserts one row per exercise sharing one package_id and never
-- checked the insert's error — so every protocol with more than one
-- exercise has been silently saving only its first exercise (or failing
-- outright) while reporting success. Table has 0 rows in production, so
-- this is safe to correct outright rather than migrate data.
alter table public.package_exercises
  drop constraint package_exercises_pkey;

alter table public.package_exercises
  alter column package_id drop identity if exists,
  alter column package_id set not null;

alter table public.package_exercises
  add column id bigint generated by default as identity primary key;
